spring:
  datasource:
    url: jdbc:hsqldb:file:mypath/mydb
    username: joe
    password: password
    driver-class-name: org.hsqldb.jdbcDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
